codecov:
  notify:
    # must be equal to the total number of parallel jobs in a CI pipeline
    # (Postgres versions x test types x test modes x OSes minus excluded
    # combinations)
    after_n_builds: 10

# datapagemap.c/.h are copied from Postgres, so let's remove it
# from report.  Otherwise, we would have to remove some currently
# unused methods to do not spoil the report.
ignore:
  - "**/datapagemap.*"
  - "**/*datapagemap*"
  - "datapagemap.*"
  - "datapagemap.c"
  - "datapagemap.h"
