FROM ololobus/postgres-dev:stretch

USER root
RUN apt-get update
RUN apt-get -yq install python python-pip python-virtualenv

# Environment
ENV PG_BRANCH=${PG_BRANCH}
ENV LANG=C.UTF-8 PGHOME=/testdir/pgbin
ENV MODE=${MODE} TEST_CASE=${TEST_CASE} TEST_REPEATS=${TEST_REPEATS}

# Make directories
RUN	mkdir -p /testdir

COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

COPY . /testdir/ptrack
WORKDIR /testdir

# Grant privileges
RUN	chown -R postgres:postgres /testdir

USER postgres
ENTRYPOINT /run.sh
